INSERT INTO burgers (burger_name, devoured) VALUES ('Shroom', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Anything Goes', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Deluxe', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Bacon Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Vegan', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Any BurgerYour Way', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Healthy Deluxe', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Crab Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Top Burger Extra Cheese', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Turkey Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Bottomless Burger', false);
